### ISSUE TITLE
bindfields.js:14 Uncaught ReferenceError: chainedfk is not defined - Django Admin

### ISSUE THREAD

**Issue by chris-jones** [jazzband/django-smart-selects#253] opened 2018-03-17 08:28 UTC
## Checklist
<sup><sup>Put an `x` in the bracket when you have completed each task, like this: `[x]`</sup></sup>

- [x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [x] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have debugged the issue to the `smart_selects` app.
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

Error received within Google Chrome when loading Django admin page of a model with an inline model which uses smart-selects.

```JavaScript
bindfields.js:14 Uncaught ReferenceError: chainedfk is not defined
    at initItem (bindfields.js:14)
    at HTMLSelectElement.<anonymous> (bindfields.js:35)
    at Function.each (jquery-2.2.0.js:360)
    at HTMLDocument.<anonymous> (bindfields.js:34)
    at fire (jquery-2.2.0.js:3182)
    at Object.fireWith [as resolveWith] (jquery-2.2.0.js:3312)
    at Function.ready (jquery-2.2.0.js:3531)
    at HTMLDocument.completed (jquery-2.2.0.js:3547)
```

## Steps to reproduce
Environment:
- Django 1.10.7
- Latest build django-smart-selects
- Jquery (2.2.0 / 2.2.3 / 2.2.4 / 3.3.1) (multiple versions tested)

1. Configured Django Instance as specified in the installation and configuration guides.
2. Smart Selects used on a Model, which is present as an InlineForm on another model Admin page 
3. Load page

## Actual behavior
Nothing. Error in Javascript prevents the code being actioned.

## Expected behavior
Smart-selects should load two fields normally, and provide smart select functionality between them.

I actually removed all other Javascript references and inline javascript code from the HTML in order to check that there wasn't a conflicting code issue, but found nothing.

The script files are loaded in the correct order, none are 404-ing:

```HTML
<script type="text/javascript" src="/admin/jsi18n/"></script>
 <script type="text/javascript" src="/static/admin/js/core.js"></script>
 <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
 <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
 <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
 <script type="text/javascript" src="/static/admin/js/actions.js"></script>
 <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
 <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
 <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

 <script type="text/javascript" src="/static/smart-selects/admin/js/chainedfk.js"></script>
 <script type="text/javascript" src="/static/smart-selects/admin/js/bindfields.js"></script>

 <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
 <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
```
Can't for the life of me see what's wrong. I think the error being thrown-up might be misleading somehow? I even combined the smart-select Javascript together, so that there would be no scope issues.

**Comment by nazrow** [comment] 2018-03-20 11:15
+1, experiencing the exact same thing. Neither `chainedfk` nor `chainedm2m` work where they should (I have chained fields of both types in like a dozen different models).
Respective **.js** files are loaded from the same `/static/smart-selects/admin/js` folder where `bindfields.js` resides, yet console shows the functions are not defined.

I've tried cleaning up `chainedm2m.js` removing all the things I don't understand and leaving it just like this:
`function chainedm2m() { ... }`
Now the browser is able to find `chainedm2m`, but tells me that `chainedm2m.init is not a function`. Same goes for `chainedfk`.

**Comment by nazrow** [comment] 2018-03-20 12:14
Aaaand it works now. I have no idea why `chainedm2m.js` and `chainedfk.js` are written the way they are, and I intend to continue to keep away from JavaScript for as long as possible, but for now I got it to work properly by editing `chainedm2m.js` this way:

`var chainedm2m = {`
`    fireEvent: function (element, event) { ... },`
`    dismissRelatedLookupPopup: function(win, chosenId) { ... },`
`    fill_field: function (val, initial_value, elem_id, url, initial_parent, auto_choose) { ... },`
`    init: function (chainfield, url, id, value, auto_choose) { ... }`
`};`

`{ ... }`s mean that I changed nothing within the actual methods themselves.

Same goes, again, for `chainedfk`.

- since it works without `"use strict"`, I guess it's irrelevant here;
- `chainedfk` and `chainedm2m` are no functions by themselves but mere containers for their methods, so may be defined as `var name = { method: definition, ... }`;
- I barely understand all that JS scope thing and don't want to dive deeper, but written clean it works, and decorated with `(function ($) { (function chainedfk(){ ... }()); }` it doesn't.

**Comment by GrilloLuca** [comment] 2018-03-20 13:25
Hi, just tried the same exact thing and it workd for me too but with var **chainedfk** =
```

var chainedfk = {

        fireEvent: function (element, event) { ... }
        dismissRelatedLookupPopup: function (win, chosenId) { ... }
        fill_field: function (val, init_value, elem_id, url, empty_label, auto_choose) { ... }
        init: function (chainfield, url, id, init_value, empty_label, auto_choose) { ... }
};
```

**Comment by mfaulkner9294** [comment] 2018-03-21 19:49
I'm also experiencing this issue...

**Comment by christianalcantara** [comment] 2018-03-22 03:59
https://github.com/RafaDias/django-smart-selects/commit/61f182f4e56fa7f7eb1ca2fbf0fb922bb25c8a0e

**Comment by ShubhamSarda** [comment] 2018-03-26 07:37
Thanks it actually help to remove Error _"bindfields.js:14 Uncaught ReferenceError: chainedfk is not defined - Django Admin"_, but now have constant error TypeError: $ is not a function, since we removed it as function.

**Comment by blag** [comment] 2018-03-28 19:30
Hi everybody, I think I fixed this in the `js-unlinting-fixes` branch. If you are still having the issue, can you try that and tell me if it works?

You should be able to install that branch using `pip`:

```bash
pip install git+https://github.com/digi604/django-smart-selects.git@js-unlinting-fixes
```

**Comment by ashkulz** [comment] 2018-04-06 15:07
@blag: works for me on Django 1.11, thanks for the fix!

**Comment by crackjack** [comment] 2018-04-06 18:07
is there a roadmap when this is about to be merged in master and that can be available to PyPi?

**Comment by crackjack** [comment] 2018-04-06 18:57
@blag I installed it through the branch you mentioned, I see that the error is gone, but when I selected one of the chained field, the JSON response has valid data, but it never appears on the dropdown.
<img width="1408" alt="screen shot 2018-04-06 at 2 56 52 pm" src="https://user-images.githubusercontent.com/191368/38439218-d1a08dbe-39aa-11e8-8648-4918091629a6.png">

**Comment by crackjack** [comment] 2018-04-06 19:57
this fixes it https://github.com/digi604/django-smart-selects/issues/56#issuecomment-379360369

**Comment by ShubhamSarda** [comment] 2018-04-07 05:35
Fixed Worked Well, 
Make Sure You Allow Django JQuery from settings.py.

**Comment by blag** [comment] 2018-04-08 21:57
@crackjack Your fix should work for that case, but I'm confused where `j.response` is coming from. From all of the code I have seen, and from the [jQuery documentation for `$.getJSON`](http://api.jquery.com/jquery.getjson/), the `j.errors` and `j.response` aren't coming from django-smart-selects. 😕 Can you figure out where those two keys are coming from?

**Comment by crackjack** [comment] 2018-04-09 13:47
`$.getJSON` calls a `url`, the URL depends on the model name and the app name which finally calls one of the methods in `[views.py](https://github.com/digi604/django-smart-selects/blob/js-unlinting-fixes/smart_selects/views.py#L90)` that returns a JSON response with the error and the response objects.

**Comment by blag** [comment] 2018-04-12 23:57
@crackjack Right, that much I followed, but I'm confused where the JSON response is getting constructed that contains the `errors` and `response` keys. We need to track that down before deciding if this fix is correct or not.

**Comment by crackjack** [comment] 2018-04-18 15:47
@blag from the HttpResponse method. https://github.com/digi604/django-smart-selects/pull/259#discussion_r182474797

**Comment by chris-jones** [comment] 2018-05-26 05:55
Sorry it's been so long responding, I've was moved across to other projects.

Just tried the js-unlinting-fixes branch which works well for me. Anyone still having problems, just check that you run `pip` with the `--upgrade` flag, and also remember to run `manage.py collectstatic ` (if you're using the static serving option).

**Comment by ricardodani** [comment] 2018-06-04 22:40
@blag works for me on django 2.0

**Comment by CJonesie** [comment] 2018-06-12 17:23
I had the same issue and this branch fixed it for me! 
https://github.com/digi604/django-smart-selects.git@js-unlinting-fixes

thanks!

**Comment by basilrabi** [comment] 2018-06-30 05:20
`js-unlinting-fixes` branch fixes the issue for me too. Thank you!

**Comment by developer2806** [comment] 2018-07-05 09:11
Thanks worked for me too. Had to clear the cache and then it worked.
But now facing the issue while edit.

Facing the issue while editing the chained m2m field. The selected options does not appear first while editing.

But if you change the main selection for the chained field then change it back to the original value the correct data loads in the corresponding multi selected field.

Any fixes for this please?

**Comment by hjalves** [comment] 2018-07-05 14:45
Having the same problem as @developer2806

**Comment by basilrabi** [comment] 2018-07-06 14:14
For me, the 2nd-order(or more) chained foreign key field does not show its previously set value. The 1st chained foreign key field, has no issue and displays its previously set value. Maybe I am having similar issues with @developer2806  and @hjalves . When I tried the patch in #260 , the issue I'm experiencing is fixed.

**Comment by basilrabi** [comment] 2018-07-29 12:59
Just found out that `js-unlinting-fixes` does not work in AdminInline. I tried looking #136 but I don't know JS.

**Comment by richard-reece** [comment] 2018-08-29 01:18
Just ran into this and https://github.com/digi604/django-smart-selects.git@js-unlinting-fixes solved the issue for me, thanks @blag !

**Comment by ishakoktn** [comment] 2018-09-22 15:13
On version 1.5.4 have same problem as developer2806's. I turned 1.5.3 and it works.

**Comment by suikocen** [comment] 2018-10-08 02:37
Worked on Firefox, but not on Chrome?

**Comment by Kuhaneswaran** [comment] 2018-10-08 05:29
I have the same issue with @suikocen. Smart select works on Firefox but not Chrome.

**Comment by ferminarellano** [comment] 2018-10-08 22:33
js-unlinting-fixes branch fixes the issue for me. Thank you! Make sure to use the --upgrade flag when running the pip instruction and then run the collectstatic script. Using Django 1.11

**Comment by suikocen** [comment] 2018-10-09 06:14
> Worked on Firefox, but not on Chrome?

Okay, after getting the code from js-unlinting-fixes branch and clearing the browsing history, it works! 
Thank you!

**Comment by Kras4ooo** [comment] 2019-02-15 08:17
Hey @digi604 Could you merge this branch: `js-unlinting-fixes` it works well on Django 2.1.7 too.

Thanks in advance!

**Comment by Taher5253** [comment] 2019-12-30 12:09
Uncaught ReferenceError: chainedm2m is not defined
    at initItem (bindfields.js:14)
    at HTMLSelectElement.<anonymous> (bindfields.js:25)
    at Function.each (jquery.min.js:2)
    at bindfields.js:24
    at dispatch (jquery.min.js:3)
    at r.handle (jquery.min.js:3)


Getting this error on **ChainedManyToManyField** 

How can i resolve this

**Comment by kciredor** [comment] 2020-01-05 16:20
I'm giving up on this package. Anyone got a proper alternative?

**Comment by Norserium** [comment] 2020-05-05 17:29
If you are out there, if anyone is out there, there is solution of this problem.

The problem appeared in `1.5.4`. In this [commit](https://github.com/jazzband/django-smart-selects/commit/c1aeb13b9580eced652e6f0e8d5d2af6e634126d#diff-2db4cbf4011896a2ddd0a03b4e6b8ad7), to be exact.

I suppose, that @blag add `"use strict";` line to correspond linter rules. Then he noticed, that it produces error `ReferenceError: chainedfk is not defined` and rewrote the code, to replace the variable definition on function definition. But he forgot, that function that defined in another function won't be global, so this change is the reason of this bug.

So, to solve this problem you can install `1.5.3` version or try to get this library not from PyPi, but from the repository directly (this problem is solved here).

**Comment by Norserium** [comment] 2020-05-05 17:31
@manelclos you've closed the issue too early. Could you release a new version in PyPi? The most of users uses this package manager to install libraries for Python.

**Comment by manelclos** [comment] 2020-05-06 06:40
@Norserium no problem in reopening if this is still a problem. Did you reproduce using master branch?

**Comment by Norserium** [comment] 2020-05-06 08:20
@maneclos, you misunderstood me. The problem is in the last version of package in PyPi `1.5.4`. I suppose it's needed to publish new version with the last updates, because users will still encounter this problem in the future.

**Comment by manelclos** [comment] 2020-05-06 08:29
@Norserium I've got access to pypi now, I'll release ASAP

**Comment by Norserium** [comment] 2020-05-06 08:49
@manelclos, just for your information I've installed the package from the repository (master branch). This error is not reproducing now (and it shouldn't according to the last changes).

**Comment by manelclos** [comment] 2020-08-17 13:46
Closing as it works on latest release.

**Closed by manelclos** 2020-08-17 13:46 UTC
Labels: Needs feedback, Possibly fixed
